# Generated by Django 5.0 on 2023-12-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('user', '0003_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.ForeignKey(default='Beginner', on_delete=django.db.models.deletion.CASCADE, related_name='progress_user', to='dashboard.level', to_field='name'),
        ),
        migrations.AddField(
            model_name='users',
            name='mahkota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='nyawa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
